# Generated by Django 3.2 on 2021-05-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_front',
        ),
        migrations.AddField(
            model_name='product',
            name='image_side',
            field=models.ImageField(default=0, upload_to='product_pics'),
            preserve_default=False,
        ),
    ]
