# Generated by Django 3.2 on 2021-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210517_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
